[opener]
edit = [{ run = 'nvim "$@"', block = true }]
browser = [{ run = 'open "$@"', orphan = true, desc = "Open in browser" }]

[open]
prepend_rules = [
  { url = "*.html", use = ["edit", "browser", "reveal", "exif"] },
  { url = "*.htm", use = ["edit", "browser", "reveal", "exif"] },
]

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
