export ZSH="$HOME/.oh-my-zsh"

# disable oh-my-zsh themes for pure prompt
ZSH_THEME=""
ZSH_DISABLE_COMPFIX=true
source $ZSH/oh-my-zsh.sh

fpath+=("$(brew --prefix)/share/zsh/site-functions")

export BREW_HOME=$(brew --prefix)

export ZPLUG_HOME=$BREW_HOME/opt/zplug
source $ZPLUG_HOME/init.zsh
zplug "mafredri/zsh-async", from:github
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "zdharma/fast-syntax-highlighting", as:plugin, defer:2
zplug "zsh-users/zsh-autosuggestions", as:plugin, defer:2
if [[ -z "$NVIM" ]]; then
    zplug "jeffreytse/zsh-vi-mode"
fi
zplug load
# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zstyle :prompt:pure:git:branch color green

plugins=(git)

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

# proxy list
alias proxy='export http_proxy=http://127.0.0.1:7890
export https_proxy=$http_proxy'
alias unproxy='unset all_proxy http_proxy https_proxy'

alias vim='nvim'
alias zz='yazi'
eval "$(zoxide init zsh)"
